language: node_js
node_js:
- "4.2.6"
before_install:
- ./install.sh
install: ./compile.sh
deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
cache:
  directories:
  - node_modules
  - typings
  - $HOME/.rvm
